### ISSUE TITLE
Morning Session peer to peer code review

### ISSUE THREAD

**Issue by ab-noori** [torobucci/Portfolio-finish-mobile-version#5]
## Highlights 💯 
- Sectioning well
- Tagged semantically
- Best practices are followed
## Suggested Change ♻️ 
It would be better not to use the Nav element for your project cart [tags](https://github.com/torobucci/Portfolio-finish-mobile-version/blob/defd5e23aabb6df7da3d31616818ccba11d37244/index.html#L138). Because they are not navigation list.
for more detail take a look at [this](https://html.com/tags/nav/) page.

**Comment by torobucci** [comment]
@ab-noori  Thanks for the suggestion. I've understood that `nav` is best reserved for the primary navigation areas, like the main menu across the top of a page or section.
